export const STARTING_APP = "STARTING_APP";
export const APP_STARTED = "APP_STARTED";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_LOADING = "FETCH_WEATHER_LOADING";
export const FETCH_WEATHER_COMPLETED = "FETCH_WEATHER_COMPLETED";